"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const jsx_runtime_1 = require("react/jsx-runtime");
// import React from 'react'; // Not needed with new JSX transform
const react_router_dom_1 = require("react-router-dom");
const AuthContext_1 = require("./context/AuthContext");
const AppContext_1 = require("./context/AppContext");
const MainLayout_1 = require("./components/layout/MainLayout");
const Login_1 = require("./pages/Login");
const Register_1 = require("./pages/Register");
const Dashboard_1 = require("./pages/Dashboard");
const Processing_1 = require("./pages/Processing");
const AnalysisDetails_1 = require("./pages/AnalysisDetails");
const App = () => {
    return ((0, jsx_runtime_1.jsx)(AuthContext_1.AuthProvider, { children: (0, jsx_runtime_1.jsx)(AppContext_1.AppProvider, { children: (0, jsx_runtime_1.jsx)(react_router_dom_1.BrowserRouter, { children: (0, jsx_runtime_1.jsxs)(react_router_dom_1.Routes, { children: [(0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/login", element: (0, jsx_runtime_1.jsx)(Login_1.Login, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/register", element: (0, jsx_runtime_1.jsx)(Register_1.Register, {}) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/dashboard", element: (0, jsx_runtime_1.jsx)(MainLayout_1.MainLayout, { children: (0, jsx_runtime_1.jsx)(Dashboard_1.Dashboard, {}) }) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/processing", element: (0, jsx_runtime_1.jsx)(MainLayout_1.MainLayout, { children: (0, jsx_runtime_1.jsx)(Processing_1.Processing, {}) }) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/profile", element: (0, jsx_runtime_1.jsx)(MainLayout_1.MainLayout, { children: (0, jsx_runtime_1.jsx)("div", { className: "p-8", children: "Profile - Coming Soon" }) }) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/history", element: (0, jsx_runtime_1.jsx)(MainLayout_1.MainLayout, { children: (0, jsx_runtime_1.jsx)("div", { className: "p-8", children: "History - Coming Soon" }) }) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/analysis/:id", element: (0, jsx_runtime_1.jsx)(MainLayout_1.MainLayout, { children: (0, jsx_runtime_1.jsx)(AnalysisDetails_1.AnalysisDetails, {}) }) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/settings", element: (0, jsx_runtime_1.jsx)(MainLayout_1.MainLayout, { children: (0, jsx_runtime_1.jsx)("div", { className: "p-8", children: "Settings - Coming Soon" }) }) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/notifications", element: (0, jsx_runtime_1.jsx)(MainLayout_1.MainLayout, { children: (0, jsx_runtime_1.jsx)("div", { className: "p-8", children: "Notifications - Coming Soon" }) }) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/admin/users", element: (0, jsx_runtime_1.jsx)(MainLayout_1.MainLayout, { children: (0, jsx_runtime_1.jsx)("div", { className: "p-8", children: "User Management - Coming Soon" }) }) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/admin/logs", element: (0, jsx_runtime_1.jsx)(MainLayout_1.MainLayout, { children: (0, jsx_runtime_1.jsx)("div", { className: "p-8", children: "System Logs - Coming Soon" }) }) }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/", element: (0, jsx_runtime_1.jsx)(react_router_dom_1.Navigate, { to: "/dashboard", replace: true }) })] }) }) }) }));
};
exports.default = App;
//# sourceMappingURL=App.js.map